spring.application.name=openai
server.port=8088
#logging.pattern.console=%green(%d{HH:mm:ss.SSS})
spring.ai.openai.api-key=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
#spring.ai.openai.chat.model=ai/gemma3
#spring.ai.openai.chat.base-url=http://localhost:12434/engines/v1
#spring.ai.openai.api-key=dummy
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:\\Users\\soume\\OneDrive\\Documents\\chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=soumen
spring.datasource.password=12345
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.docker.compose.stop.command=down
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=spring-ai
management.endpoints.web.exposure.include=health,metrics,prometheus